name = "sb"
version = "1.0.0"

[dependencies]
gleam_stdlib = ">= 0.44.0 and < 2.0.0"
pprint = ">= 1.0.6 and < 2.0.0"
gleam_community_ansi = ">= 1.4.3 and < 2.0.0"
gleam_community_colour = ">= 2.0.2 and < 3.0.0"
gleam_yielder = ">= 1.1.0 and < 2.0.0"
gleam_http = ">= 4.1.1 and < 5.0.0"
gleam_json = ">= 3.0.2 and < 4.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
