name = "sb"
version = "1.0.0"

[dependencies]
gleam_community_ansi = ">= 1.4.3 and < 2.0.0"
gleam_community_colour = ">= 2.0.2 and < 3.0.0"
gleam_stdlib = ">= 0.44.0 and < 2.0.0"
forms = { path = "pkgs/forms" }
extra = { path = "pkgs/extra" }
frontend = { path = "pkgs/frontend" }
extra_erlang = { path = "pkgs/extra_erlang" }
wisp = ">= 2.0.0 and < 3.0.0"
gleam_erlang = ">= 1.3.0 and < 2.0.0"
filepath = ">= 1.1.2 and < 2.0.0"
envoy = ">= 1.0.2 and < 2.0.0"
mist = ">= 5.0.3 and < 6.0.0"
gleam_otp = ">= 1.1.0 and < 2.0.0"
lustre = ">= 5.3.5 and < 6.0.0"
lustre_portal = ">= 1.0.0 and < 2.0.0"
gleam_http = ">= 4.1.1 and < 5.0.0"
gleam_json = ">= 3.0.2 and < 4.0.0"

[dev-dependencies]
birdie = ">= 1.4.0 and < 2.0.0"
gleeunit = ">= 1.0.0 and < 2.0.0"
pprint = ">= 1.0.6 and < 2.0.0"
