name = "extra_erlang"
version = "1.0.0"

[erlang]
extra_applications = ["inets", "ssl"]

[dependencies]
gleam_stdlib = ">= 0.44.0 and < 2.0.0"
yamerl = ">= 0.10.0 and < 1.0.0"
exception = ">= 2.1.0 and < 3.0.0"
extra = { path = "../extra" }
gleam_erlang = ">= 1.3.0 and < 2.0.0"
lustre = ">= 5.3.5 and < 6.0.0"
gleam_http = ">= 4.2.0 and < 5.0.0"
